// Dropdown options
const options = [
  "AGARTALA",
  "AGRA",
  "AHMEDABAD",
  "AJMER",
  "AKOLA",
  "ALAPPUZHA",
  "ALIGARH",
  "ALLAHABAD",
  "ALWAR",
  "AMBALA",
  "AMRAVATI",
  "AMRITSAR",
  "ANAND",
  "ANANTAPUR",
  "ANANTNAG",
  "ANGUL",
  "ANJANGAON",
  "ANKLESHWAR",
  "ARARIA",
  "ARCOT",
  "ARDHANAPUR",
  "ARJUNGANJ",
  "ARUPPUKOTTAI",
  "ASANSOL",
  "ASHOKNAGAR",
  "AURANGABAD",
  "AZAMGARH",
  "BADLAPUR",
  "BAGALKOT",
  "BAGH",
  "BAGPAT",
  "BAHARAMPUR",
  "BAHRAICH",
  "BAIKUNTHPUR",
  "BAKHTIYARPUR",
  "BALAGHAT",
  "BALANGIR",
  "BALASORE",
  "BALLIA",
  "BALRAMPUR",
  "BALURGHAT",
  "BANDA",
  "BANDIKUI",
  "BANGALORE",
  "BANGARAPET",
  "BANKA",
  "BANKURA",
  "BANSWARA",
  "BANTWAL",
  "BARAMATI",
  "BARAMULLA",
  "BARAN",
  "BARAUT",
  "BARBIL",
  "BARDHAMAN",
  "BAREILLY",
  "BARGARH",
  "BARMER",
  "BARNALA",
  "BARPETA",
  "BARRACKPORE",
  "BARSHI",
  "BARTAN",
  "BASIRHAT",
  "BATALA",
  "BATHINDA",
  "BATHINDA",
  "BEAWAR",
  "BEGUSARAI",
  "BELGAUM",
  "BELLAMPALLE",
  "BELTANGADY",
  "BENGALURU",
  "BETUL",
  "BHADRAK",
  "BHAGALPUR",
  "BHAGAPURANA",
  "BHAGWANPUR",
  "BHARATPUR",
  "BHARUCH",
  "BHAVNAGAR",
  "BHIKANGAON",
  "BHILAI",
  "BHILWARA",
  "BHIND",
  "BHOPAL",
  "BHUBANESHWAR",
  "BHUBANESWAR",
  "BHUJ",
  "BIAORA",
  "BIDAR",
  "BIJAPUR",
  "BIJNOR",
  "BILASIPARA",
  "BILASPUR",
  "BILASPUR",
  "BIRPARA",
  "BISHNUPUR",
  "BOKARO",
  "BONGAIGAON",
  "BUDAUN",
  "BULDHANA",
  "BURHANPUR",
  "CALANGUTE",
  "CHALISGAON",
  "CHAMARAJANAGAR",
  "CHAMPA",
  "CHAMPAWAT",
  "CHAMPHAI",
  "CHANDAUSI",
  "CHANDIGARH",
  "CHANDRAPUR",
  "CHAPRA",
  "CHAS",
  "CHENNAI",
  "CHHATARPUR",
  "CHHINDWARA",
  "CHIKMAGALUR",
  "CHILAKALURIPET",
  "CHINGLEPET",
  "CHINSURAH",
  "CHITTORGARH",
  "CHITTUR",
  "CHITTOOR",
  "CHURU",
  "COIMBATORE",
  "COOCH BEHAR",
  "CUDDALORE",
  "CUTTACK",
  "DALTONGANJ",
  "DAMAN",
  "DAMOH",
  "DARBHANGA",
  "DARBHANGA",
  "DARYAGANJ",
  "DAUSA",
  "DAVANAGERE",
  "DEESA",
  "DEHRA DUN",
  "DEHRI",
  "DELHI",
  "DEOGHAR",
  "DEORIA",
  "DEWAS",
  "DHAKA",
  "DHAMTARI",
  "DHANBAD",
  "DHARAMSHALA",
  "DHARAPURAM",
  "DHARMAPURI",
  "DHARWAD",
  "DHULE",
  "DIBRUGARH",
  "DIGBOI",
  "DIMAPUR",
  "DINDIGUL",
  "DINDORI",
  "DINDORI",
  "DISA",
  "DIU",
  "DODA",
  "DOHAD",
  "DOMBIVLI",
  "DUM DUM",
  "DUNGARPUR",
  "DURG",
  "DURGAPUR",
  "DWARAKA",
  "EAST DELHI",
  "ELURU",
  "ERNAKULAM",
  "ETAH",
  "ETAWAH",
  "FAIZABAD",
  "FARIDABAD",
  "FARIDKOT",
  "FARUKHABAD",
  "FAZILKA",
  "FIROZABAD",
  "GADAG",
  "GADCHIROLI",
  "GADHADA",
  "GADHINAGAR",
  "GADWAL",
  "GAJUWAKA",
  "GANDHIDHAM",
  "GANDHINAGAR",
  "GANGANAGAR",
  "GANGAPUR",
  "GANJAM",
  "GANNAVARAM",
  "GARHWA",
  "GAYA",
  "GHANSOLI",
  "GHARAUNDA",
  "GHATAL",
  "GHATAMPUR",
  "GHATANJI",
  "GHATSILA",
  "GHOSI",
  "GHUGUS",
  "GIDDALUR",
  "GIRIDIH",
  "GOALPARA",
  "GODDA",
  "GOKAK",
  "GOLA GOKARANNATH",
  "GONDAL",
  "GONDIA",
  "GONDA",
  "GORAKHPUR",
  "GOREGA",
  "GOREGAON",
  "GOVANDI",
  "GOVERDHAN",
  "GUDALUR",
  "GUDUR",
  "GUJARAT",
  "GULBARGA",
  "GUMMIDIPUNDI",
  "GUNA",
  "GUNTUR",
  "GURGAON",
  "GUWAHATI",
  "GWALIOR",
  "HABRA",
  "HADAPSAR",
  "HAJIPUR",
  "HALISAHAR",
  "HALOL",
  "HALVAD",
  "HAMIRPUR",
  "HANUMAN JUNCTION",
  "HAPUR",
  "HARDASAH",
  "HARIDWAR",
  "HARIHAR",
  "HARIPUR",
  "HASSAN",
  "HASTINAPUR",
  "HATHRAS",
  "HAVERI",
  "HINDUPUR",
  "HINJILICUT",
  "HISAR",
  "HOSHANGABAD",
  "HOSHIARPUR",
  "HOSPET",
  "HOSUR",
  "HOWRAH",
  "HUDA",
  "HUZURABAD",
  "HYDERABAD",
  "IB",
  "IBRAMPUR",
  "ICHALKARANJI",
  "IDAPPADI",
  "IGATPURI",
  "ILKAL",
  "ILLALUR",
  "IMPHAL",
  "INDORE",
  "IPUR",
  "IRINJALAKUDA",
  "ISMAILABAD",
  "ITANAGAR",
  "ITARSI",
  "JABALPUR",
  "JADCHERLA",
  "JADUGODA",
  "JAGDALPUR",
  "JAGGAIAHPET",
  "JAGRAON",
  "JAIGAON",
  "JAINAGAR",
  "JAIPUR",
  "JAITARAN",
  "JAKHAL",
  "JALALABAD",
  "JALALPURA",
  "JALANDHAR",
  "JALAUN",
  "JALGAON",
  "JALOR",
  "JALPAIGURI",
  "JAMKHANDI",
  "JAMMU",
  "JAMNAGAR",
  "JAMSHEDPUR",
  "JANGAON",
  "JANGAREDDIGUDEM",
  "JANGHAI",
  "JANJGIR",
  "JASPUR",
  "JAUNPUR",
  "JAWAD",
  "JAYAMKONDACHOLAPURAM",
  "JAYSINGPUR",
  "JETPUR",
  "JEYPORE",
  "JHABUA",
  "JHAGADIA",
  "JHAJJAR",
  "JHALAWAR",
  "JHANSI",
  "JHARGRAM",
  "JHARSUGUDA",
  "JHUNJHUNU",
  "JIND",
  "JODHPUR",
  "JORHAT",
  "JUNAGADH",
  "KABIRDHAM",
  "KADAPA",
  "KADIRI",
  "KAGAL",
  "KAILARAS",
  "KAIMUR",
  "KAITHAL",
  "KAKINADA",
  "KALAHANDI",
  "KALAMB",
  "KALANAUR",
  "KALIMPONG",
  "KALOL",
  "KALYAN",
  "KAMALAPUR",
  "KAMAREDDY",
  "KAMATHIPURA",
  "KANCHIPURAM",
  "KANHANGAD",
  "KANIGIRI",
  "KANJIRAPPALLY",
  "KANKER",
  "KANKINARA",
  "KANKROLI",
  "KANNUR",
  "KANPUR",
  "KAPADVANJ",
  "KAPURTHALA",
  "KARAD",
  "KARAIKAL",
  "KARAIKKUDI",
  "KARANJA",
  "KARANPRAYAG",
  "KARAWAL NAGAR",
  "KARIMGANJ",
  "KARIMNAGAR",
  "KARNAL",
  "KARUNAGAPALLY",
  "KARUR",
  "KARWAR",
  "KASARAGOD",
  "KASHIPUR",
  "KATHUA",
  "KATIHAR",
  "KATNI",
  "KATOL",
  "KATTAPPANA",
  "KAVALI",
  "KAWARDHA",
  "KAYANKULAM",
  "KENDRAPARA",
  "KENDUAPADA",
  "KESHOD",
  "KHAMGAON",
  "KHAMMAM",
  "KHANAPUR",
  "KHANNA",
  "KHARAGPUR",
  "KHARGONE",
  "KHATAULI",
  "KHATIMA",
  "KHEDA",
  "KHOPOLI",
  "KHURAI",
  "KHURJA",
  "KHUSHALGARH",
  "KICHHA",
  "KISHANGANJ",
  "KISHANGARH",
  "KISHANPUR",
  "KISHOREGANJ",
  "KITHORE",
  "KODAD",
  "KODAGU",
  "KODERMA",
  "KOHIMA",
  "KOLAR",
  "KOLHAPUR",
  "KOLLAM",
  "KOLLEGAL",
  "KOPARGAON",
  "KOPPAL",
  "KORAPUT",
  "KORBA",
  "KORIYA",
  "KOTA",
  "KOTDWAR",
  "KOTHAMANGALAM",
  "KOTHAPETA",
  "KOTKAPURA",
  "KOTMA",
  "KOTRA",
  "KOTRADAKHAN",
  "KOTRANG",
  "KOTRASEKHAR",
  "KOTRESHWAR",
  "KOTWA",
  "KOVILPATTI",
  "KOVVUR",
  "KOZHIKODE",
  "KULGAM",
  "KULITHALAI",
  "KULLU",
  "KUMAON",
  "KUMBAKONAM",
  "KUNDAPURA",
  "KUNIGAL",
  "URNOOL",
  "KURNOOL",
  "KURUKSHETRA",
  "KURUNDWAD",
  "KUSHINAGAR",
  "KUSHMANDA",
  "KUSHWAHA",
  "KUSHPUR",
  "KUTCH",
  "KUTCH",
  "KUTHUPARAMBA",
  "KUTIYANA",
  "KUWAIT",
  "KUZHITHURAI",
  "LAHARPUR",
  "LAHORE",
  "LAKHIMPUR",
  "LAKHISARAI",
  "LALITPUR",
  "LALSOT",
  "LANKA",
  "LANSING",
  "LATHI",
  "LATUR",
  "LEH",
  "LILONG",
  "LONAR",
  "LONAVLA",
  "LONDON",
  "LONGOWAL",
];

function showDropdown() {
  const dropdownOptions = document.getElementById("dropdownoptionslocation");
  dropdownOptions.style.display = "block";
  filterOptions(); // Filter options initially
}

// Filter dropdown options based on input
function filterOptions() {
  const input = document.getElementById("option2Input").value.toLowerCase();
  const dropdownOptions = document.getElementById("dropdownoptionslocation");

  // Clear previous options
  dropdownOptions.innerHTML = "";

  // Filter and add new options
  options.forEach((option) => {
    if (option.toLowerCase().includes(input)) {
      const a = document.createElement("a");
      a.href = "#";
      a.textContent = option;
      a.onclick = function () {
        selectOption(option);
      };
      dropdownOptions.appendChild(a);
    }
  });

  // Display or hide dropdown based on filtered options
  dropdownOptions.style.display =
    dropdownOptions.children.length > 0 ? "block" : "none";
}

// Select option
function selectOption(option) {
  const input = document.getElementById("option2Input");
  input.value = option;
  // If you need to perform additional actions when an option is selected, you can add them here.

  // Close dropdown
  const dropdownOptions = document.getElementById("dropdownoptionslocation");
  dropdownOptions.style.display = "none";
}

// Close dropdown when clicking outside
window.onclick = function (event) {
  if (!event.target.matches("#option2Input")) {
    const dropdownOptions = document.getElementById("dropdownoptionslocation");
    dropdownOptions.style.display = "none";
  }
};
